

export const bouquets = [

    {
        "id": "1",
        "cаtegoryName": "М'ясні",
        "categoryURL": "https://i.ibb.co/3mb0Yd5/meat-category.png",
        "bouquets": [
            {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "2",
        "cаtegoryName": "Бокси",
        "categoryURL": "https://i.ibb.co/fFFb7R0/boxes-category.png",
        "bouquets": [
            {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "3",
        "cаtegoryName": "До 500 грн",
        "categoryURL": "https://i.ibb.co/f0BncxN/till500-category.png",
        "bouquets": [
              {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "4",
        "cаtegoryName": "Збери сам",
        "categoryURL": "https://i.ibb.co/8zGkRWw/takeaway-category.png",
        "bouquets": [
              {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "5",
        "cаtegoryName": "Не їстівні",
        "categoryURL": "https://i.ibb.co/FzFGd9Z/noeat-category.png",
        "bouquets": [
              {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "6",
        "cаtegoryName": "500-1000 грн",
        "categoryURL": "https://i.ibb.co/J5Swvhm/500till1000-category.png",
        "bouquets": [
             {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "7",
        "cаtegoryName": "Дитячі",
        "categoryURL": "https://i.ibb.co/myCSFQg/children-category.png",
        "bouquets": [
              {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "8",
        "cаtegoryName": "Горіхові",
        "categoryURL": "https://i.ibb.co/hR3MQdk/nuts-category.png",
        "bouquets": [
            {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "9",
        "cаtegoryName": "1000-2000 грн",
        "categoryURL": "https://i.ibb.co/z2pP5Cr/1000till2000-category.png",
        "bouquets": [
             {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "10",
        "cаtegoryName": "Фруктові",
        "categoryURL": "https://i.ibb.co/nBPKMck/fruits-category.png",
        "bouquets": [
              {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "11",
        "cаtegoryName": "Солодкі",
        "categoryURL": "https://i.ibb.co/Nnb6cPQ/sweet-category.png",
        "bouquets": [
             {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
    {
        "id": "12",
        "cаtegoryName": "Понад 2000",
        "categoryURL": "https://i.ibb.co/5s98rgz/more2000-category.png",
        "bouquets": [
             {
                "id": "1",
                "name": "Старий друг",
                "imgURL": "https://i.ibb.co/HphF66n/bouquet-old-Friend.png",
                "width": "60",
                "height": "40",
                "weight": "4",
                "price": "800",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "перець чилі" },{ "id": "2", "name": "розмарин" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }, {"id": "6", "name": "ковбаса “Кбааносі”" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,33 л Кількість пляшок: 2-5",
            },
            {
                "id": "2",
                "name": "Молочник",
                "imgURL": "https://i.ibb.co/pjTp7Fw/bouquet-milk.jpg",
                "width": "60",
                "height": "40",
                "weight": "3",
                "price": "500",
                "season": "круглий рік",
                "ingredients": [{ "id": "1", "name": "молоко" },{ "id": "2", "name": "хліб" }, {"id": "3", "name": "сир сулугуні копчений 2 види" }, {"id": "4", "name": "мисливські ковбаски 2 види" }, {"id": "5", "name": "ковбаса сиро-копчена “Фует”" }],
                "warnings": "! Молоко НЕ входить у вартість букету !",
                "details": "Напій на ваш вибір у пляшці об’ємом 1 л Кількість пляшок: 1",
            },
            {
                "id": "3",
                "name": "Пиво с раками",
                "imgURL": "https://i.ibb.co/JvnX6Mb/bouguet-crayfish.jpg",
                "width": "60",
                "height": "40",
                "weight": "5",
                "price": "500",
                "season": "літо",
                "ingredients": [{ "id": "1", "name": "раки" },{ "id": "2", "name": "пиво" }, {"id": "3", "name": "овочі" }],
                "warnings": "! Алкоголь НЕ входить у вартість букету !",
                "details": "Пиво на ваш вибір у склі об’ємом 0,5 л Кількість пляшок: 1",
            },
        ]
    },
]
